version: "3.9"

services:
  api:
    build: .
    container_name: server_fastAPI
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app/app

#comando para correr el contenedor 
#docker-compose up --build
